# Generated by Django 2.0.6 on 2018-12-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_auto_20181205_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='answer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
