# Generated by Django 2.0.6 on 2018-12-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_auto_20181205_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='answer',
            new_name='a1',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='a2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='a3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='a4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='level',
            field=models.CharField(default='something', max_length=100),
            preserve_default=False,
        ),
    ]
