# Generated by Django 2.0.6 on 2018-12-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_auto_20181205_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=257)),
                ('email', models.EmailField(max_length=200)),
                ('nameFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testApp.TestModel')),
            ],
        ),
    ]
