# Generated by Django 2.0.6 on 2018-12-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_usersetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w1', models.CharField(blank=True, max_length=100)),
                ('w2', models.CharField(blank=True, max_length=100)),
                ('w3', models.CharField(blank=True, max_length=100)),
                ('w4', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
