# Generated by Django 2.0.6 on 2018-12-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_vocabularymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='q1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='q2',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='q3',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='q4',
            field=models.TextField(max_length=200),
        ),
    ]
