# Generated by Django 2.0.6 on 2018-12-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_auto_20181206_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='q1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='q2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='q3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='q4',
            field=models.CharField(max_length=200),
        ),
    ]
