# Generated by Django 2.0.6 on 2018-12-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_auto_20181206_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='timer',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
