# Generated by Django 2.0.6 on 2018-12-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_questionmodel_timer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='timer',
            new_name='setTime',
        ),
    ]
