# Generated by Django 2.0.6 on 2018-12-06 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_auto_20181206_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='setTime',
            new_name='timeSetter',
        ),
    ]
